# Generated by Django 5.2.6 on 2025-09-11 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_code', models.IntegerField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=200)),
                ('room_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('hours', models.IntegerField()),
                ('rooms', models.ManyToManyField(blank=True, related_name='guests', to='Room.room')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_hours', models.IntegerField(default=24)),
                ('room_state', models.BooleanField(default=True)),
                ('capacity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Capacity', to='Room.room')),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Code', to='Room.room')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Name', to='Room.room')),
            ],
        ),
    ]
